const express = require('express')
const router = express.Router()
const multer = require('multer');
const Kepler = require('./../controllers/KeplerController')

const upload = multer();

router.get('/getusers', Kepler.getUsers)
router.get('/getkdsGastosVehicular', Kepler.getkdsGastosVehicular)
router.get('/getkdms', Kepler.getKdms)
router.get('/getkdsregion', Kepler.getKdsRegion)
router.get('/getkdsdirope', Kepler.getKdsDirOpe)
router.get('/getkdsregionsuc', Kepler.getKdsRegionSuc)
router.get('/getkdsdirre', Kepler.getKdsDirRe)
router.get('/getkdud', Kepler.getKdud)
router.get('/getKdsCardexVehiculos', Kepler.getKdsCardexVehiculos)
router.get('/searchClient/:client', Kepler.searchClient)
router.get('/getSubsidiaryClient/:client', Kepler.getSubsidiaryClient)
router.get('/getClientById/:client', Kepler.getClientById)
router.get('/getFolio', Kepler.getFolio)
router.get('/getValidationFolio', Kepler.getValidationFolio)
router.get('/KDS_CHECKLIST', Kepler.KDS_CHECKLIST)
router.get('/getValidations', Kepler.getValidations)
router.get('/getKdsEventos', Kepler.getKdsEventos)
router.get('/getkdsCobranzaSeg', Kepler.getkdsCobranzaSeg)
router.get('/getKdsNivelesCobranza', Kepler.getKdsNivelesCobranza)

router.post('/auth', Kepler.auth)
router.post('/saveChecklist', upload.none(), Kepler.saveChecklist)
router.post('/updateGastosVehicular', upload.none(), Kepler.updateGastosVehicular)
router.post('/updateKm', upload.none(), Kepler.updateckdsCardexVehiculos)
router.post('/saveValidation', upload.none(), Kepler.saveValidation)
router.post('/updateValidation', upload.none(), Kepler.updateValidation)
router.post('/updateCardexStatus', upload.none(), Kepler.updateCardexStatus)
router.post('/updateStatusGasto', upload.none(), Kepler.updateStatusGasto)
router.post('/saveKdsKilometrajeGps', upload.none(), Kepler.saveKdsKilometrajeGps)
router.post('/updateEstatusCardex', upload.none(), Kepler.updateEstatusCardex)
router.post('/saveKdsEventos', upload.none(), Kepler.kdsEventos)
router.post('/updateKdsEventos', upload.none(), Kepler.updateKdsEventos)
router.post('/updatekdsCobranzaSeg', upload.none(), Kepler.updatekdsCobranzaSeg)
router.post('/savekdsCobranzaLog', upload.none(), Kepler.savekdsCobranzaLog)
router.post('/saveKdsGastosK', upload.none(), Kepler.saveKdsGastosK)
router.post('/updateKdsGastosK', upload.none(), Kepler.updateKdsGastosK)
module.exports = router

