const express = require('express')
const router = express.Router()
const Kepler = require('./../controllers/KeplerController')

router.get('/getusers', Kepler.getUsers)
router.get('/getkdsGastosVehicular', Kepler.getkdsGastosVehicular)
router.get('/getkdms', Kepler.getKdms)
router.get('/getkdsregion', Kepler.getKdsRegion)
router.get('/getkdsdirope', Kepler.getKdsDirOpe)
router.get('/getkdsregionsuc', Kepler.getKdsRegionSuc)
router.get('/getkdsdirre', Kepler.getKdsDirRe)
router.get('/getkdud', Kepler.getKdud)
router.get('/getKdsCardexVehiculos', Kepler.getKdsCardexVehiculos)
router.get('/searchClient/:client', Kepler.searchClient)
router.get('/getSubsidiaryClient/:client', Kepler.getSubsidiaryClient)
router.get('/getClientById/:client', Kepler.getClientById)
router.get('/getFolio', Kepler.getFolio)

router.post('/auth', Kepler.auth)
router.post('/saveChecklist', Kepler.saveChecklist)
router.post('/updateGastosVehicular', Kepler.updateGastosVehicular)
module.exports = router